add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
read_only = " "

[git_branch]
symbol = " "

[lua]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
